// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collector.proto

package org_demo_collector

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitResponse_InitResponseEnum int32

const (
	InitResponse_CONTINUE     InitResponse_InitResponseEnum = 0
	InitResponse_REPEAT_AFTER InitResponse_InitResponseEnum = 1
	InitResponse_MOVE_TO      InitResponse_InitResponseEnum = 2
)

var InitResponse_InitResponseEnum_name = map[int32]string{
	0: "CONTINUE",
	1: "REPEAT_AFTER",
	2: "MOVE_TO",
}

var InitResponse_InitResponseEnum_value = map[string]int32{
	"CONTINUE":     0,
	"REPEAT_AFTER": 1,
	"MOVE_TO":      2,
}

func (x InitResponse_InitResponseEnum) String() string {
	return proto.EnumName(InitResponse_InitResponseEnum_name, int32(x))
}

func (InitResponse_InitResponseEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{1, 0}
}

// tag::InitRequest[]
type InitRequest struct {
	GatewayId            string   `protobuf:"bytes,1,opt,name=gatewayId,proto3" json:"gatewayId,omitempty"`
	GatewayType          string   `protobuf:"bytes,2,opt,name=gatewayType,proto3" json:"gatewayType,omitempty"`
	GatewayVersion       string   `protobuf:"bytes,3,opt,name=gatewayVersion,proto3" json:"gatewayVersion,omitempty"`
	ConfigurationVersion string   `protobuf:"bytes,4,opt,name=configurationVersion,proto3" json:"configurationVersion,omitempty"`
	BatchesCount         int32    `protobuf:"varint,5,opt,name=batchesCount,proto3" json:"batchesCount,omitempty"`
	BatchesSize          int32    `protobuf:"varint,6,opt,name=batchesSize,proto3" json:"batchesSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *InitRequest) GetGatewayType() string {
	if m != nil {
		return m.GatewayType
	}
	return ""
}

func (m *InitRequest) GetGatewayVersion() string {
	if m != nil {
		return m.GatewayVersion
	}
	return ""
}

func (m *InitRequest) GetConfigurationVersion() string {
	if m != nil {
		return m.ConfigurationVersion
	}
	return ""
}

func (m *InitRequest) GetBatchesCount() int32 {
	if m != nil {
		return m.BatchesCount
	}
	return 0
}

func (m *InitRequest) GetBatchesSize() int32 {
	if m != nil {
		return m.BatchesSize
	}
	return 0
}

type InitResponse struct {
	Action               InitResponse_InitResponseEnum `protobuf:"varint,1,opt,name=action,proto3,enum=org.demo.collector.InitResponse_InitResponseEnum" json:"action,omitempty"`
	Pause                int32                         `protobuf:"varint,2,opt,name=pause,proto3" json:"pause,omitempty"`
	Url                  string                        `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	BatchesCount         int32                         `protobuf:"varint,4,opt,name=batchesCount,proto3" json:"batchesCount,omitempty"`
	NewConfiguratuion    string                        `protobuf:"bytes,5,opt,name=newConfiguratuion,proto3" json:"newConfiguratuion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

func (m *InitResponse) GetAction() InitResponse_InitResponseEnum {
	if m != nil {
		return m.Action
	}
	return InitResponse_CONTINUE
}

func (m *InitResponse) GetPause() int32 {
	if m != nil {
		return m.Pause
	}
	return 0
}

func (m *InitResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *InitResponse) GetBatchesCount() int32 {
	if m != nil {
		return m.BatchesCount
	}
	return 0
}

func (m *InitResponse) GetNewConfiguratuion() string {
	if m != nil {
		return m.NewConfiguratuion
	}
	return ""
}

// tag::BatchRequest[]
type MeterMeasurement struct {
	Timestamp            int32    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Measurement          int32    `protobuf:"varint,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeterMeasurement) Reset()         { *m = MeterMeasurement{} }
func (m *MeterMeasurement) String() string { return proto.CompactTextString(m) }
func (*MeterMeasurement) ProtoMessage()    {}
func (*MeterMeasurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{2}
}

func (m *MeterMeasurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeterMeasurement.Unmarshal(m, b)
}
func (m *MeterMeasurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeterMeasurement.Marshal(b, m, deterministic)
}
func (m *MeterMeasurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeterMeasurement.Merge(m, src)
}
func (m *MeterMeasurement) XXX_Size() int {
	return xxx_messageInfo_MeterMeasurement.Size(m)
}
func (m *MeterMeasurement) XXX_DiscardUnknown() {
	xxx_messageInfo_MeterMeasurement.DiscardUnknown(m)
}

var xxx_messageInfo_MeterMeasurement proto.InternalMessageInfo

func (m *MeterMeasurement) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MeterMeasurement) GetMeasurement() int32 {
	if m != nil {
		return m.Measurement
	}
	return 0
}

type MeterData struct {
	MeterUuid            []byte              `protobuf:"bytes,1,opt,name=meterUuid,proto3" json:"meterUuid,omitempty"`
	Data                 []*MeterMeasurement `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MeterData) Reset()         { *m = MeterData{} }
func (m *MeterData) String() string { return proto.CompactTextString(m) }
func (*MeterData) ProtoMessage()    {}
func (*MeterData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{3}
}

func (m *MeterData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeterData.Unmarshal(m, b)
}
func (m *MeterData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeterData.Marshal(b, m, deterministic)
}
func (m *MeterData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeterData.Merge(m, src)
}
func (m *MeterData) XXX_Size() int {
	return xxx_messageInfo_MeterData.Size(m)
}
func (m *MeterData) XXX_DiscardUnknown() {
	xxx_messageInfo_MeterData.DiscardUnknown(m)
}

var xxx_messageInfo_MeterData proto.InternalMessageInfo

func (m *MeterData) GetMeterUuid() []byte {
	if m != nil {
		return m.MeterUuid
	}
	return nil
}

func (m *MeterData) GetData() []*MeterMeasurement {
	if m != nil {
		return m.Data
	}
	return nil
}

type BatchRequest struct {
	BatchUuid            []byte       `protobuf:"bytes,1,opt,name=batchUuid,proto3" json:"batchUuid,omitempty"`
	Data                 []*MeterData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BatchRequest) Reset()         { *m = BatchRequest{} }
func (m *BatchRequest) String() string { return proto.CompactTextString(m) }
func (*BatchRequest) ProtoMessage()    {}
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{4}
}

func (m *BatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchRequest.Unmarshal(m, b)
}
func (m *BatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchRequest.Marshal(b, m, deterministic)
}
func (m *BatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchRequest.Merge(m, src)
}
func (m *BatchRequest) XXX_Size() int {
	return xxx_messageInfo_BatchRequest.Size(m)
}
func (m *BatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchRequest proto.InternalMessageInfo

func (m *BatchRequest) GetBatchUuid() []byte {
	if m != nil {
		return m.BatchUuid
	}
	return nil
}

func (m *BatchRequest) GetData() []*MeterData {
	if m != nil {
		return m.Data
	}
	return nil
}

type BatchResponse struct {
	BatchUuid            []byte   `protobuf:"bytes,1,opt,name=batchUuid,proto3" json:"batchUuid,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchResponse) Reset()         { *m = BatchResponse{} }
func (m *BatchResponse) String() string { return proto.CompactTextString(m) }
func (*BatchResponse) ProtoMessage()    {}
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{5}
}

func (m *BatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchResponse.Unmarshal(m, b)
}
func (m *BatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchResponse.Marshal(b, m, deterministic)
}
func (m *BatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchResponse.Merge(m, src)
}
func (m *BatchResponse) XXX_Size() int {
	return xxx_messageInfo_BatchResponse.Size(m)
}
func (m *BatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchResponse proto.InternalMessageInfo

func (m *BatchResponse) GetBatchUuid() []byte {
	if m != nil {
		return m.BatchUuid
	}
	return nil
}

func (m *BatchResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *BatchResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// tag::CompleteRequest[]
type CompleteRequest struct {
	MonitoringData       string   `protobuf:"bytes,1,opt,name=monitoringData,proto3" json:"monitoringData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteRequest) Reset()         { *m = CompleteRequest{} }
func (m *CompleteRequest) String() string { return proto.CompactTextString(m) }
func (*CompleteRequest) ProtoMessage()    {}
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{6}
}

func (m *CompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteRequest.Unmarshal(m, b)
}
func (m *CompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteRequest.Marshal(b, m, deterministic)
}
func (m *CompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteRequest.Merge(m, src)
}
func (m *CompleteRequest) XXX_Size() int {
	return xxx_messageInfo_CompleteRequest.Size(m)
}
func (m *CompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteRequest proto.InternalMessageInfo

func (m *CompleteRequest) GetMonitoringData() string {
	if m != nil {
		return m.MonitoringData
	}
	return ""
}

type CompleteResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteResponse) Reset()         { *m = CompleteResponse{} }
func (m *CompleteResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteResponse) ProtoMessage()    {}
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{7}
}

func (m *CompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteResponse.Unmarshal(m, b)
}
func (m *CompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteResponse.Marshal(b, m, deterministic)
}
func (m *CompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteResponse.Merge(m, src)
}
func (m *CompleteResponse) XXX_Size() int {
	return xxx_messageInfo_CompleteResponse.Size(m)
}
func (m *CompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteResponse proto.InternalMessageInfo

func (m *CompleteResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CompleteResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("org.demo.collector.InitResponse_InitResponseEnum", InitResponse_InitResponseEnum_name, InitResponse_InitResponseEnum_value)
	proto.RegisterType((*InitRequest)(nil), "org.demo.collector.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "org.demo.collector.InitResponse")
	proto.RegisterType((*MeterMeasurement)(nil), "org.demo.collector.MeterMeasurement")
	proto.RegisterType((*MeterData)(nil), "org.demo.collector.MeterData")
	proto.RegisterType((*BatchRequest)(nil), "org.demo.collector.BatchRequest")
	proto.RegisterType((*BatchResponse)(nil), "org.demo.collector.BatchResponse")
	proto.RegisterType((*CompleteRequest)(nil), "org.demo.collector.CompleteRequest")
	proto.RegisterType((*CompleteResponse)(nil), "org.demo.collector.CompleteResponse")
}

func init() { proto.RegisterFile("collector.proto", fileDescriptor_9305884a292fdf82) }

var fileDescriptor_9305884a292fdf82 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0xd9, 0x8d, 0xf3, 0x6b, 0x26, 0xa6, 0x35, 0xab, 0x0a, 0x59, 0x15, 0x88, 0x60, 0xaa,
	0x2a, 0x07, 0x14, 0xd1, 0x70, 0x81, 0x13, 0x2a, 0xc1, 0x48, 0x91, 0x68, 0x83, 0x36, 0x4e, 0xaf,
	0xd1, 0xd6, 0x59, 0x82, 0xa5, 0x78, 0xd7, 0xac, 0xd7, 0x54, 0xe5, 0x43, 0x70, 0xe2, 0x7b, 0xf2,
	0x15, 0xd0, 0xae, 0x37, 0xb1, 0xf3, 0xa7, 0xe1, 0x96, 0x79, 0xfb, 0x66, 0xe6, 0xcd, 0xf3, 0x4c,
	0xe0, 0x38, 0xe6, 0x8b, 0x05, 0x8d, 0x25, 0x17, 0xbd, 0x4c, 0x70, 0xc9, 0x11, 0xe2, 0x62, 0xde,
	0x9b, 0xd1, 0x94, 0xf7, 0x56, 0x2f, 0xc1, 0x1f, 0x0b, 0xda, 0x43, 0x96, 0x48, 0x4c, 0xbf, 0x17,
	0x34, 0x97, 0xe8, 0x29, 0xb4, 0xe6, 0x44, 0xd2, 0x3b, 0x72, 0x3f, 0x9c, 0xf9, 0x56, 0xc7, 0xea,
	0xb6, 0x70, 0x05, 0xa0, 0x0e, 0xb4, 0x4d, 0x10, 0xdd, 0x67, 0xd4, 0xb7, 0xf5, 0x7b, 0x1d, 0x42,
	0xe7, 0x70, 0x64, 0xc2, 0x1b, 0x2a, 0xf2, 0x84, 0x33, 0xff, 0x40, 0x93, 0x36, 0x50, 0xd4, 0x87,
	0x93, 0x98, 0xb3, 0xaf, 0xc9, 0xbc, 0x10, 0x44, 0x26, 0x9c, 0x2d, 0xd9, 0x0d, 0xcd, 0xde, 0xf9,
	0x86, 0x02, 0x70, 0x6f, 0x89, 0x8c, 0xbf, 0xd1, 0x7c, 0xc0, 0x0b, 0x26, 0x7d, 0xa7, 0x63, 0x75,
	0x1d, 0xbc, 0x86, 0x29, 0x85, 0x26, 0x1e, 0x27, 0x3f, 0xa9, 0xdf, 0xd4, 0x94, 0x3a, 0x14, 0xfc,
	0xb6, 0xc1, 0x2d, 0x27, 0xce, 0x33, 0xce, 0x72, 0x8a, 0x86, 0xd0, 0x24, 0xb1, 0xea, 0xa3, 0xe7,
	0x3d, 0xea, 0x5f, 0xf4, 0xb6, 0x7d, 0xea, 0xd5, 0x33, 0xd6, 0x82, 0x90, 0x15, 0x29, 0x36, 0x05,
	0xd0, 0x09, 0x38, 0x19, 0x29, 0xf2, 0xd2, 0x19, 0x07, 0x97, 0x01, 0xf2, 0xe0, 0xa0, 0x10, 0x0b,
	0x63, 0x84, 0xfa, 0xb9, 0x35, 0x49, 0x63, 0xc7, 0x24, 0xaf, 0xe0, 0x31, 0xa3, 0x77, 0x83, 0x95,
	0x11, 0x85, 0x52, 0xe8, 0xe8, 0x1a, 0xdb, 0x0f, 0xc1, 0x7b, 0xf0, 0x36, 0x55, 0x21, 0x17, 0x0e,
	0x07, 0xa3, 0xeb, 0x68, 0x78, 0x3d, 0x09, 0xbd, 0xff, 0x90, 0x07, 0x2e, 0x0e, 0xbf, 0x84, 0x97,
	0xd1, 0xf4, 0xf2, 0x53, 0x14, 0x62, 0xcf, 0x42, 0x6d, 0xf8, 0xff, 0x6a, 0x74, 0x13, 0x4e, 0xa3,
	0x91, 0x67, 0x07, 0x18, 0xbc, 0x2b, 0x2a, 0xa9, 0xb8, 0xa2, 0x24, 0x2f, 0x04, 0x4d, 0x29, 0xd3,
	0xcb, 0x20, 0x93, 0x94, 0xe6, 0x92, 0xa4, 0x99, 0x36, 0xc7, 0xc1, 0x15, 0xa0, 0xac, 0x4e, 0x2b,
	0xb2, 0x19, 0xb9, 0x0e, 0x05, 0x31, 0xb4, 0x74, 0xcd, 0x8f, 0x44, 0x12, 0x55, 0x2c, 0x55, 0xc1,
	0xa4, 0x48, 0xca, 0xcd, 0x72, 0x71, 0x05, 0xa0, 0xb7, 0xd0, 0x98, 0x11, 0x49, 0x7c, 0xbb, 0x73,
	0xd0, 0x6d, 0xf7, 0xcf, 0x76, 0x7d, 0x82, 0x4d, 0x79, 0x58, 0x67, 0x04, 0x53, 0x70, 0x3f, 0x28,
	0xdf, 0x6a, 0x1b, 0xac, 0x7d, 0xac, 0xf7, 0x59, 0x01, 0xe8, 0x62, 0xad, 0xcf, 0xb3, 0x07, 0xfb,
	0x28, 0xc9, 0xa6, 0xc1, 0x1c, 0x1e, 0x99, 0x06, 0x66, 0x61, 0xf6, 0x77, 0x78, 0x02, 0x4d, 0x41,
	0xf3, 0x62, 0x51, 0x3a, 0x72, 0x88, 0x4d, 0xa4, 0xec, 0x9a, 0xd1, 0x3c, 0x16, 0x49, 0x26, 0xab,
	0xb3, 0xa8, 0x43, 0xc1, 0x3b, 0x38, 0x1e, 0xf0, 0x34, 0x5b, 0x50, 0x49, 0x97, 0xc3, 0x9c, 0xc3,
	0x51, 0xca, 0x59, 0x22, 0xb9, 0x48, 0xd8, 0x5c, 0x69, 0x32, 0x37, 0xb9, 0x81, 0x06, 0x9f, 0xc1,
	0xab, 0x52, 0x8d, 0xcc, 0x4a, 0x88, 0xb5, 0x4f, 0x88, 0xbd, 0x25, 0xa4, 0xff, 0xcb, 0x86, 0x93,
	0x30, 0x8d, 0xc9, 0x60, 0xe9, 0xc9, 0x98, 0x8a, 0x1f, 0x49, 0xac, 0x4e, 0xa5, 0xa1, 0xb6, 0x0c,
	0x3d, 0x7f, 0xf8, 0x44, 0xb4, 0xee, 0xd3, 0xce, 0xbf, 0x6e, 0x08, 0x45, 0xd0, 0x1a, 0x53, 0x36,
	0xd3, 0xce, 0xa2, 0x9d, 0xf4, 0xfa, 0x57, 0x3d, 0x7d, 0xb1, 0x87, 0x51, 0x56, 0xec, 0x5a, 0xaf,
	0x2d, 0x34, 0x81, 0xc3, 0xa5, 0x0f, 0xe8, 0xe5, 0xae, 0x94, 0x0d, 0x83, 0x4f, 0xcf, 0xf6, 0x93,
	0xca, 0xd2, 0xb7, 0x4d, 0xfd, 0x07, 0xfa, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xf5,
	0x3c, 0xc7, 0x53, 0x05, 0x00, 0x00,
}
