// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queryRuntime.proto

package org_demo_queryRuntime

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryResponse_InitResponseEnum int32

const (
	QueryResponse_CONTINUE  QueryResponse_InitResponseEnum = 0
	QueryResponse_RECONNECT QueryResponse_InitResponseEnum = 1
	QueryResponse_MOVE_TO   QueryResponse_InitResponseEnum = 2
)

var QueryResponse_InitResponseEnum_name = map[int32]string{
	0: "CONTINUE",
	1: "RECONNECT",
	2: "MOVE_TO",
}

var QueryResponse_InitResponseEnum_value = map[string]int32{
	"CONTINUE":  0,
	"RECONNECT": 1,
	"MOVE_TO":   2,
}

func (x QueryResponse_InitResponseEnum) String() string {
	return proto.EnumName(QueryResponse_InitResponseEnum_name, int32(x))
}

func (QueryResponse_InitResponseEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{1, 0}
}

type GetDataResponse_InitResponseEnum int32

const (
	GetDataResponse_CONTINUE  GetDataResponse_InitResponseEnum = 0
	GetDataResponse_RECONNECT GetDataResponse_InitResponseEnum = 1
)

var GetDataResponse_InitResponseEnum_name = map[int32]string{
	0: "CONTINUE",
	1: "RECONNECT",
}

var GetDataResponse_InitResponseEnum_value = map[string]int32{
	"CONTINUE":  0,
	"RECONNECT": 1,
}

func (x GetDataResponse_InitResponseEnum) String() string {
	return proto.EnumName(GetDataResponse_InitResponseEnum_name, int32(x))
}

func (GetDataResponse_InitResponseEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{4, 0}
}

// tag::QueryRequest[]
type QueryRequest struct {
	KeysFilter           []string `protobuf:"bytes,1,rep,name=keysFilter,proto3" json:"keysFilter,omitempty"`
	FrequencyOfSend      int32    `protobuf:"varint,2,opt,name=frequencyOfSend,proto3" json:"frequencyOfSend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetKeysFilter() []string {
	if m != nil {
		return m.KeysFilter
	}
	return nil
}

func (m *QueryRequest) GetFrequencyOfSend() int32 {
	if m != nil {
		return m.FrequencyOfSend
	}
	return 0
}

type QueryResponse struct {
	Action               QueryResponse_InitResponseEnum `protobuf:"varint,1,opt,name=action,proto3,enum=org.demo.queryRuntime.QueryResponse_InitResponseEnum" json:"action,omitempty"`
	StreamUid            string                         `protobuf:"bytes,2,opt,name=streamUid,proto3" json:"streamUid,omitempty"`
	Url                  string                         `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{1}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetAction() QueryResponse_InitResponseEnum {
	if m != nil {
		return m.Action
	}
	return QueryResponse_CONTINUE
}

func (m *QueryResponse) GetStreamUid() string {
	if m != nil {
		return m.StreamUid
	}
	return ""
}

func (m *QueryResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// tag::GetDataRequest[]
type GetDataRequest struct {
	StreamUid            string   `protobuf:"bytes,1,opt,name=streamUid,proto3" json:"streamUid,omitempty"`
	FromTime             string   `protobuf:"bytes,2,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{2}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetStreamUid() string {
	if m != nil {
		return m.StreamUid
	}
	return ""
}

func (m *GetDataRequest) GetFromTime() string {
	if m != nil {
		return m.FromTime
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{3}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetDataResponse struct {
	Action               GetDataResponse_InitResponseEnum `protobuf:"varint,1,opt,name=action,proto3,enum=org.demo.queryRuntime.GetDataResponse_InitResponseEnum" json:"action,omitempty"`
	StreamUid            string                           `protobuf:"bytes,2,opt,name=streamUid,proto3" json:"streamUid,omitempty"`
	Timestamp            int32                            `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []*KeyValue                      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{4}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetAction() GetDataResponse_InitResponseEnum {
	if m != nil {
		return m.Action
	}
	return GetDataResponse_CONTINUE
}

func (m *GetDataResponse) GetStreamUid() string {
	if m != nil {
		return m.StreamUid
	}
	return ""
}

func (m *GetDataResponse) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetDataResponse) GetData() []*KeyValue {
	if m != nil {
		return m.Data
	}
	return nil
}

// tag::CompleteRequest[]
type CompleteRequest struct {
	MonitoringData       string   `protobuf:"bytes,1,opt,name=monitoringData,proto3" json:"monitoringData,omitempty"`
	StreamUid            string   `protobuf:"bytes,2,opt,name=streamUid,proto3" json:"streamUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteRequest) Reset()         { *m = CompleteRequest{} }
func (m *CompleteRequest) String() string { return proto.CompactTextString(m) }
func (*CompleteRequest) ProtoMessage()    {}
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{5}
}

func (m *CompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteRequest.Unmarshal(m, b)
}
func (m *CompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteRequest.Marshal(b, m, deterministic)
}
func (m *CompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteRequest.Merge(m, src)
}
func (m *CompleteRequest) XXX_Size() int {
	return xxx_messageInfo_CompleteRequest.Size(m)
}
func (m *CompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteRequest proto.InternalMessageInfo

func (m *CompleteRequest) GetMonitoringData() string {
	if m != nil {
		return m.MonitoringData
	}
	return ""
}

func (m *CompleteRequest) GetStreamUid() string {
	if m != nil {
		return m.StreamUid
	}
	return ""
}

type CompleteResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteResponse) Reset()         { *m = CompleteResponse{} }
func (m *CompleteResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteResponse) ProtoMessage()    {}
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_708aea475bcb7082, []int{6}
}

func (m *CompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteResponse.Unmarshal(m, b)
}
func (m *CompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteResponse.Marshal(b, m, deterministic)
}
func (m *CompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteResponse.Merge(m, src)
}
func (m *CompleteResponse) XXX_Size() int {
	return xxx_messageInfo_CompleteResponse.Size(m)
}
func (m *CompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteResponse proto.InternalMessageInfo

func (m *CompleteResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CompleteResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("org.demo.queryRuntime.QueryResponse_InitResponseEnum", QueryResponse_InitResponseEnum_name, QueryResponse_InitResponseEnum_value)
	proto.RegisterEnum("org.demo.queryRuntime.GetDataResponse_InitResponseEnum", GetDataResponse_InitResponseEnum_name, GetDataResponse_InitResponseEnum_value)
	proto.RegisterType((*QueryRequest)(nil), "org.demo.queryRuntime.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "org.demo.queryRuntime.QueryResponse")
	proto.RegisterType((*GetDataRequest)(nil), "org.demo.queryRuntime.GetDataRequest")
	proto.RegisterType((*KeyValue)(nil), "org.demo.queryRuntime.KeyValue")
	proto.RegisterType((*GetDataResponse)(nil), "org.demo.queryRuntime.GetDataResponse")
	proto.RegisterType((*CompleteRequest)(nil), "org.demo.queryRuntime.CompleteRequest")
	proto.RegisterType((*CompleteResponse)(nil), "org.demo.queryRuntime.CompleteResponse")
}

func init() { proto.RegisterFile("queryRuntime.proto", fileDescriptor_708aea475bcb7082) }

var fileDescriptor_708aea475bcb7082 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x9c, 0xbf, 0x26, 0x37, 0x6d, 0x62, 0x8d, 0x3e, 0x90, 0x15, 0x2a, 0xb0, 0x0c, 0x14,
	0xaf, 0x0c, 0x4a, 0x85, 0xd8, 0xb0, 0x0b, 0x06, 0x15, 0x68, 0xac, 0xb8, 0x69, 0x41, 0xb0, 0x40,
	0xc6, 0xb9, 0x89, 0x46, 0xf5, 0x78, 0xdc, 0xf1, 0xb8, 0x92, 0xf7, 0xbc, 0x0c, 0xef, 0xc2, 0x43,
	0x21, 0xff, 0x35, 0xa9, 0x45, 0xda, 0xc2, 0xce, 0xf7, 0xcc, 0xdc, 0x33, 0xe7, 0x9c, 0x3b, 0x63,
	0x20, 0x17, 0x09, 0x8a, 0xd4, 0x4d, 0x42, 0x49, 0x19, 0x5a, 0x91, 0xe0, 0x92, 0x93, 0x7b, 0x5c,
	0xac, 0xac, 0x05, 0x32, 0x6e, 0x6d, 0x2e, 0x1a, 0x9f, 0x61, 0x77, 0x96, 0xd7, 0x78, 0x91, 0x60,
	0x2c, 0xc9, 0x43, 0x80, 0x73, 0x4c, 0xe3, 0xb7, 0x34, 0x90, 0x28, 0x34, 0x45, 0x6f, 0x9a, 0x3d,
	0x77, 0x03, 0x21, 0x26, 0x0c, 0x97, 0x22, 0xdb, 0x1b, 0xfa, 0xa9, 0xb3, 0x3c, 0xc1, 0x70, 0xa1,
	0x35, 0x74, 0xc5, 0x6c, 0xbb, 0x75, 0xd8, 0xf8, 0xa5, 0xc0, 0x5e, 0x49, 0x1d, 0x47, 0x3c, 0x8c,
	0x91, 0x1c, 0x43, 0xc7, 0xf3, 0x25, 0xe5, 0xa1, 0xa6, 0xe8, 0x8a, 0x39, 0x18, 0xbf, 0xb4, 0xfe,
	0xa8, 0xc9, 0xba, 0xd6, 0x65, 0x1d, 0x85, 0x54, 0x56, 0x85, 0x1d, 0x26, 0xcc, 0x2d, 0x49, 0xc8,
	0x3e, 0xf4, 0x62, 0x29, 0xd0, 0x63, 0xa7, 0xb4, 0x10, 0xd1, 0x73, 0xd7, 0x00, 0x51, 0xa1, 0x99,
	0x88, 0x40, 0x6b, 0xe6, 0x78, 0xf6, 0x69, 0xbc, 0x06, 0xb5, 0xce, 0x45, 0x76, 0xa1, 0x3b, 0x71,
	0xa6, 0xf3, 0xa3, 0xe9, 0xa9, 0xad, 0xfe, 0x47, 0xf6, 0xa0, 0xe7, 0xda, 0x13, 0x67, 0x3a, 0xb5,
	0x27, 0x73, 0x55, 0x21, 0x7d, 0xd8, 0x39, 0x76, 0xce, 0xec, 0x6f, 0x73, 0x47, 0x6d, 0x18, 0xef,
	0x61, 0xf0, 0x0e, 0xe5, 0x1b, 0x4f, 0x7a, 0x55, 0x54, 0xd7, 0xce, 0x57, 0xea, 0xe7, 0x8f, 0xa0,
	0xbb, 0x14, 0x9c, 0xcd, 0x29, 0xc3, 0x52, 0xdc, 0x55, 0x6d, 0x8c, 0xa1, 0xfb, 0x01, 0xd3, 0x33,
	0x2f, 0x48, 0x30, 0xd3, 0x79, 0x8e, 0x69, 0xd9, 0x9f, 0x7d, 0x92, 0xff, 0xa1, 0x7d, 0x99, 0x2d,
	0x95, 0xc1, 0x16, 0x85, 0xf1, 0xa3, 0x01, 0xc3, 0x2b, 0x01, 0x65, 0xa0, 0x4e, 0x2d, 0xd0, 0x57,
	0x5b, 0x02, 0xad, 0xf5, 0xfd, 0x6b, 0xa4, 0xfb, 0xd0, 0xcb, 0xe8, 0x62, 0xe9, 0xb1, 0x28, 0x0f,
	0xb6, 0xed, 0xae, 0x01, 0x72, 0x08, 0xad, 0x85, 0x27, 0x3d, 0xad, 0xa5, 0x37, 0xcd, 0xfe, 0xf8,
	0xd1, 0x16, 0x29, 0x95, 0x6f, 0x37, 0xdf, 0x6c, 0x3c, 0xff, 0xcb, 0x99, 0x18, 0x9f, 0x60, 0x38,
	0xe1, 0x2c, 0x0a, 0x50, 0x62, 0x35, 0x87, 0x03, 0x18, 0x30, 0x1e, 0x52, 0xc9, 0x05, 0x0d, 0x57,
	0x99, 0xcf, 0x32, 0xcc, 0x1a, 0x7a, 0xb3, 0x39, 0xe3, 0x23, 0xa8, 0x6b, 0xe2, 0x32, 0xdf, 0xfb,
	0xd0, 0x11, 0x18, 0x27, 0x81, 0xcc, 0x19, 0xbb, 0x6e, 0x59, 0x11, 0x1d, 0xfa, 0x0b, 0x8c, 0x7d,
	0x41, 0xa3, 0x3c, 0xfc, 0x82, 0x6b, 0x13, 0x1a, 0xff, 0x6c, 0xc0, 0x03, 0x9b, 0xf9, 0xde, 0x6c,
	0xc3, 0x7b, 0x26, 0xe2, 0x04, 0xc5, 0x25, 0xf5, 0x91, 0xcc, 0xa0, 0x95, 0xf9, 0x26, 0x8f, 0x6f,
	0x7e, 0x02, 0xb9, 0xc1, 0xd1, 0x93, 0xbb, 0xbc, 0x13, 0xf2, 0x05, 0x76, 0x56, 0xc5, 0x9c, 0xc9,
	0xd3, 0xdb, 0xee, 0x41, 0xc1, 0x7b, 0x70, 0xb7, 0xeb, 0xf2, 0x42, 0x21, 0x5f, 0xa1, 0x5b, 0x85,
	0x43, 0xb6, 0x75, 0xd5, 0xc6, 0x32, 0x7a, 0x76, 0xeb, 0xbe, 0x82, 0xfe, 0x7b, 0x27, 0xff, 0x41,
	0x1d, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x72, 0xc5, 0xc6, 0x53, 0xb6, 0x04, 0x00, 0x00,
}
